## a compose file the imports 5 modules from a local repo when run
version: '2'
services:
  base:
    image: akshmakov/cvs2git-migrator
    environment:
      CVSROOT: "/srv/cvsroot"
    volumes:
      - ./cvs2git.options:/etc/cvs2git-migrator/cvs2git.options
      - ./cvs:/srv/cvsroot
      - ./output:/workdir
    command: --no-cache 
  migrate: 
    extends: base
    environment:
      CVS2GIT_MODULE: ${CVS_FOLDER}